projeto: devops
AWS_access_key: "{{ AWSAccessKeyId }}"
AWS_secret_key: "{{ AWSSecretKey }}"
instance_type: t2.micro
security_group: "{{ projeto }}-ws-sg"
image_ami: ami-07ebfd5b3428b6f4d
KeyPairDev: "{{ projeto }}-key"
region: us-east-1
count: 3
vpc_cidr_block: 10.0.0.0/16
cidr_block: 10.0.1.16/28
vpc_name: "{{ projeto }}-vpc"
name_service: app-node
route_tag: "{{ projeto }}-route"
sub_tag: "{{ projeto }}-subnet"
name_aim_user_s3: digitals3