- name: Setup Ansible Hosts Group
  hosts: localhost
  gather_facts: False

  vars_files:
    - vars/aws_credentials.yml
    - vars/aws.yml

  tasks:
    - name: Get Info EC2
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": ["app-node-1"]
        aws_access_key: "{{ AWS_access_key }}"
        aws_secret_key: "{{ AWS_secret_key }}"
      register: ec2

    - name: Add instance EC2 public IP to host group
      add_host: hostname={{ item.public_dns_name }} groups=ec2jenkins
      loop: "{{ ec2.instances }}"

# Inicia a configuracao da EC2
- name: "Ansible para configurar VM"
  hosts: ec2jenkins
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Linux - Atualizando todos os pacotes
      package:
        name: '*'
        state: latest

    - name: Verifica pacotes essenciais do python
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
        - ansible
    
    - name: Download required roles docker (desktop local)
      local_action: command ansible-galaxy install nickjj.docker
      become: false

    - name: Download required roles java
      local_action: command ansible-galaxy install geerlingguy.java 
      become: false

    - name: Download required roles jenkins
      local_action: command ansible-galaxy install geerlingguy.jenkins 
      become: false

      